# Generated by Django 4.0.1 on 2022-01-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisetable',
            name='exercise',
            field=models.CharField(default=11, max_length=120),
            preserve_default=False,
        ),
    ]
