# Generated by Django 4.0.1 on 2022-01-28 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodtracker', '0004_alter_exercise_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_group',
        ),
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.URLField(default='t.ly/rvVm'),
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.URLField(default='t.ly/6C6A'),
        ),
        migrations.AlterField(
            model_name='food',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
