# Generated by Django 4.0.1 on 2022-01-29 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtracker', '0006_alter_exercise_image_alter_food_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='image',
        ),
        migrations.RemoveField(
            model_name='food',
            name='image',
        ),
    ]
