# Generated by Django 4.0.1 on 2022-01-28 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodtracker', '0002_exercisetable_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.CharField(max_length=120)),
                ('duration', models.CharField(max_length=60)),
                ('calories', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='FoodTable',
            new_name='Food',
        ),
        migrations.DeleteModel(
            name='ExerciseTable',
        ),
    ]
