# Generated by Django 4.0.1 on 2022-01-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtracker', '0005_remove_food_food_group_exercise_image_food_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.URLField(default='https://st4.depositphotos.com/2171279/26456/v/600/depositphotos_264562442-stock-illustration-young-fit-woman-doing-plank.jpg'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.URLField(default='https://cdn5.vectorstock.com/i/1000x1000/84/94/healthy-food-concept-vector-13638494.jpg'),
        ),
    ]
